name: CI

on:
  push:
    branches: ["main"]
    tags: ["helm/**", "v*"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VER: "3.19"

jobs:

  ############
  # Building #
  ############

  appcast:
    name: appcast
    # Despite this CI job is not always needed, we intentionally keep it running
    # always, because we want the `docker` CI job to depend on it, and GitHub
    # Actions doesn't provide any conditional depending at the moment.
    #if: ${{ startsWith(github.ref, 'refs/tags/v')
    #     || github.ref == 'refs/heads/main'
    #     || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ startsWith(github.ref, 'refs/tags/v') && 'gh-pages' || '' }}
          fetch-depth: 0 # for correct versioning via `git describe --tags`
      - name: Fetch Makefile from the upstream
        run: git checkout ${{ github.ref }} -- Makefile
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Parse semver versions from Git tag
        id: semver
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/v(((([0-9]+)\.[0-9]+)\.[0-9]+)(-.+)?)$'
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - run: mkdir -p appcast/ .cache/
      - run: make appcast.item
        env:
          link: ${{ startsWith(github.ref, 'refs/tags/v') && secrets.ARTIFACTS_STABLE || secrets.ARTIFACTS_MAIN }}
          notes: ${{ !startsWith(github.ref, 'refs/tags/v') && secrets.APPCAST_NOTES || '' }}
          version: ${{ steps.semver.outputs.group1 }}

      - run: |
          cp appcast/${{ steps.semver.outputs.group1 }}.xml \
              .cache/${{ steps.semver.outputs.group1 }}.xml
          rm -f appcast/appcast.xml
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - run: make appcast.xml out=.cache/appcast.xml

      - uses: actions/upload-artifact@v4
        with:
          name: appcast-${{ github.run_number }}
          path: .cache/*.xml
          if-no-files-found: error
          retention-days: 1

  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - web
    runs-on: ${{ (contains('ios macos', matrix.platform) && 'macos-latest')
              || (matrix.platform == 'windows'           && 'windows-latest')
              ||                                            'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Unshallow the repository in order for `PubspecBuilder` and its
          # `git describe` to work.
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VER }}
          channel: stable
          cache: true

      - run: make flutter.pub

      - name: Parse semver versions from Git tag
        id: semver
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/v(((([0-9]+)\.[0-9]+)\.[0-9]+)(-.+)?)$'
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - run: make flutter.build platform=${{ matrix.platform }} profile=yes

      - name: Parse application name from Git repository name
        id: app
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.repository }}
          regex: '^${{ github.repository_owner }}/(.+)$'

      - run: mkdir artifacts/
      - uses: thedoctor0/zip-release@0.7.6
        with:
          custom: ${{ (runner.os == 'Windows' && ' ') || '--symlinks' }}  # preserve symlinks, instead of copying files
          filename: ${{ github.workspace }}/artifacts/${{ steps.app.outputs.group1 }}-${{ matrix.platform }}.zip
          directory: 'build/web'

      - name: Generate SHA256 checksums
        run: ${{ (runner.os == 'Windows'
                  && 'forfiles /M *.zip /C "cmd /c sha256sum @file > @file.sha256sum"')
              || (runner.os == 'macOS'
                  && 'ls -1 | xargs -I {} sh -c "shasum -a 256 {} > {}.sha256sum"')
              ||     'ls -1 | xargs -I {} sh -c "sha256sum {} > {}.sha256sum"' }}
        working-directory: artifacts/
      - name: Show generated SHA256 checksums
        run: ${{ (runner.os == 'Windows'
                  && 'type *.sha256sum')
              ||     'cat *.sha256sum' }}
        working-directory: artifacts/

      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}-${{ github.run_number }}
          path: artifacts/
          if-no-files-found: error
          retention-days: 1

  docker:
    needs: ["appcast", "build"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: build-web-${{ github.run_number }}
      - run: mkdir -p build/web/
      - run: unzip *.zip -d build/web/

      - uses: actions/download-artifact@v4
        with:
          name: appcast-${{ github.run_number }}
          path: build/web/
        if: ${{ startsWith(github.ref, 'refs/tags/v') ||
                github.ref == 'refs/heads/main' }}

      - run: make docker.image no-cache=yes
                  tag=build-${{ github.run_number }}

      - run: make docker.tar to-file=.cache/image.tar
                  tags=build-${{ github.run_number }}
      - uses: actions/upload-artifact@v4
        with:
          name: docker-${{ github.run_number }}
          path: .cache/image.tar
          if-no-files-found: error
          retention-days: 1




  #############
  # Releasing #
  #############

  appcast-push:
    name: appcast push
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - release-github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Parse semver versions from Git tag
        id: semver
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/v(((([0-9]+)\.[0-9]+)\.[0-9]+)(-.+)?)$'

      - run: mkdir -p appcast/
      - run: rm -f appcast/appcast.xml

      - uses: actions/download-artifact@v4
        with:
          name: appcast-${{ github.run_number }}
          path: appcast/

      - name: Update Appcast index
        run: |
          set -ex

          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'

          git checkout --orphan orphan-gh-pages
          git add --all
          git commit -m 'Release ${{ steps.semver.outputs.group1 }} version'
          git branch -M orphan-gh-pages gh-pages
          git push --force origin gh-pages

  release-github:
    name: release (GitHub)
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
      - docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse semver versions from Git tag
        id: semver
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref }}
          regex: '^refs/tags/v(((([0-9]+)\.[0-9]+)\.[0-9]+)(-.+)?)$'
      - name: Verify Git tag version matches `pubspec.yaml` version
        run: |
          test "${{ steps.semver.outputs.group1 }}" \
            == "$(grep -m1 'version: ' pubspec.yaml | cut -d ' ' -f2)"

      - name: Parse CHANGELOG link
        id: changelog
        run: echo ::set-output
                  name=link::${{ github.server_url }}/${{ github.repository }}/blob/v${{ steps.semver.outputs.group1 }}/CHANGELOG.md#$(sed -n '/^## \[${{ steps.semver.outputs.group1 }}\]/{s/^## \[\(.*\)\][^0-9]*\([0-9].*\)/\1--\2/;s/[^0-9a-z-]*//g;p;}' CHANGELOG.md)
      - name: Parse milestone link
        id: milestone
        run: echo ::set-output
                  name=link::${{ github.server_url }}/${{ github.repository }}/milestone/$(sed -n '/^## \[${{ steps.semver.outputs.group1 }}\]/,/Milestone/{s/.*milestone.\([0-9]*\).*/\1/p;}' CHANGELOG.md)

      - uses: actions/download-artifact@v4
        with:
          name: build-web-${{ github.run_number }}
          path: artifacts/

      - name: Show artifacts SHA256 checksums
        run: cat *.sha256sum
        working-directory: artifacts/

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.semver.outputs.group1 }}
          body: >
            [Changelog](${{ steps.changelog.outputs.link }}) |
            [Milestone](${{ steps.milestone.outputs.link }})
          files: |
            artifacts/*.apk
            artifacts/*.aab
            artifacts/*.zip
            artifacts/*.sha256sum
          fail_on_unmatched_files: true
          prerelease: ${{ contains(steps.semver.outputs.group1, '-') }}
